# Generated by Django 2.2 on 2021-04-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roboexpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('selected', models.BooleanField(null=True)),
                ('bid', models.IntegerField(default=0)),
                ('mail_delivered', models.BooleanField(default=False)),
                ('abstract', models.FileField(null=True, upload_to='docs/roboexpo/abstracts')),
            ],
        ),
    ]
