# Generated by Django 2.1.7 on 2020-02-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roboexpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('team_mates', models.TextField()),
                ('selected', models.NullBooleanField()),
                ('bid', models.IntegerField(default=0)),
            ],
        ),
    ]
