# Generated by Django 2.2 on 2021-04-22 06:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roboexpo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roboexpo',
            name='team_mates',
            field=models.ManyToManyField(related_name='team_mates', to=settings.AUTH_USER_MODEL),
        ),
    ]
