# Generated by Django 2.1.7 on 2020-02-19 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roboexpo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roboexpo',
            name='mail_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='roboexpo',
            name='team_mates',
        ),
        migrations.AddField(
            model_name='roboexpo',
            name='team_mates',
            field=models.ManyToManyField(related_name='team_mates', to=settings.AUTH_USER_MODEL),
        ),
    ]
