# Generated by Django 3.1.7 on 2021-03-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboexpo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roboexpo',
            name='abstract',
            field=models.FileField(null=True, upload_to='docs/roboexpo/abstracts'),
        ),
        migrations.AddField(
            model_name='roboexpo',
            name='mail_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roboexpo',
            name='selected',
            field=models.BooleanField(null=True),
        ),
        migrations.RemoveField(
            model_name='roboexpo',
            name='team_mates',
        ),
    ]
