# Generated by Django 2.1.7 on 2020-02-19 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboexpo', '0002_auto_20200219_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='roboexpo',
            name='abstract',
            field=models.FileField(default='', upload_to='docs/roboexpo/abstracts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roboexpo',
            name='team_mates',
            field=models.ManyToManyField(null=True, related_name='team_mates', to=settings.AUTH_USER_MODEL),
        ),
    ]
