# Generated by Django 3.1.7 on 2021-03-14 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboexpo', '0002_auto_20210314_1426'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roboexpo',
            name='team_mates',
            field=models.ManyToManyField(related_name='team_mates', to=settings.AUTH_USER_MODEL),
        ),
    ]
