# Generated by Django 3.1.7 on 2021-03-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='app',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='webteam')),
                ('name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=50)),
                ('linkedin', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='DIY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='img/diy')),
                ('desc', models.CharField(max_length=1000)),
                ('mentor', models.CharField(max_length=50)),
                ('members', models.CharField(max_length=200)),
                ('file', models.FileField(default='', upload_to='docs/diy')),
            ],
        ),
        migrations.CreateModel(
            name='sponsors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('sponsor_type', models.CharField(blank=True, max_length=150, null=True)),
                ('website', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='sponsors/')),
            ],
        ),
        migrations.CreateModel(
            name='web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='webteam')),
                ('name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=50)),
                ('linkedin', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
        migrations.AddField(
            model_name='fyi',
            name='head',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='fyi',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
