# Generated by Django 3.2 on 2021-05-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_auto_20210521_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='extras/gallery')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='diy',
            name='file',
            field=models.FileField(default='', upload_to='extras/diy/docs'),
        ),
        migrations.AlterField(
            model_name='diy',
            name='photo',
            field=models.ImageField(upload_to='extras/diy/img'),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='extras/sponsors'),
        ),
        migrations.AlterField(
            model_name='web',
            name='img',
            field=models.ImageField(default='', upload_to='extras/webteam'),
        ),
    ]
