# Generated by Django 2.1.7 on 2020-02-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_auto_20200219_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='appteam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='webteam')),
                ('name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=50)),
                ('linkedin', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='webteam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='webteam')),
                ('name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=50)),
                ('linkedin', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
    ]
