# Generated by Django 3.2 on 2021-05-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_auto_20210524_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=5000)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
