# Generated by Django 2.1.7 on 2020-02-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_appteam_webteam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appteam',
            new_name='app',
        ),
        migrations.RenameModel(
            old_name='webteam',
            new_name='web',
        ),
    ]
