# Generated by Django 3.2 on 2021-05-30 06:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0005_auto_20210529_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='diy_fyi',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='extras/diy_fyi/docs'),
        ),
        migrations.AlterField(
            model_name='diy_fyi',
            name='desc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='diy_fyi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='extras/diy_fyi/img'),
        ),
        migrations.AlterField(
            model_name='diy_fyi',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diy_fyi',
            name='members',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, null=True, size=8),
        ),
        migrations.AlterField(
            model_name='diy_fyi',
            name='mentor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diy_fyi',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
