# Generated by Django 2.2 on 2021-04-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(blank=True, choices=[('01', 'Rank 01'), ('02', 'Rank 02'), ('03', 'Rank 03'), ('PC', 'Participation')], max_length=2, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event/Certificate/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=1000)),
                ('event_type', models.CharField(blank=True, choices=[('OO', 'ONLINE'), ('AB', 'ABSTRACT BASED'), ('PB', 'PITCHING BASED'), ('HT', 'HACKATHON'), ('WS', 'WORKSHOP')], max_length=2, null=True)),
                ('payment', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('selected', models.BooleanField(default=False, null=True)),
                ('bid', models.IntegerField(default=0)),
                ('mail_delivered', models.BooleanField(default=False)),
                ('abstract', models.FileField(null=True, upload_to='event/docs/abstracts')),
                ('image', models.ImageField(null=True, upload_to='event/docs/image')),
                ('college', models.CharField(max_length=150, null=True)),
                ('payment', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
