# Generated by Django 2.1.7 on 2020-02-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
