# Generated by Django 3.1.7 on 2021-03-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210317_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='events.CertImage'),
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='image',
        ),
        migrations.AddField(
            model_name='workshop',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='events.CertImage'),
        ),
    ]
