# Generated by Django 3.2 on 2021-05-31 16:22

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.PathAndRename('event/Certificate/')),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(null=True, upload_to=events.models.PathAndRename2('event/docs/image')),
        ),
    ]
