# Generated by Django 3.1.7 on 2021-03-17 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20210317_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('selected', models.BooleanField(null=True)),
                ('bid', models.IntegerField(default=0)),
                ('mail_delivered', models.BooleanField(default=False)),
                ('abstract', models.FileField(null=True, upload_to='event/docs/abstracts')),
                ('image', models.ImageField(null=True, upload_to='event/docs/image')),
                ('college', models.CharField(blank=True, max_length=150, null=True)),
                ('payment', models.BooleanField(default=False)),
                ('team_mates', models.ManyToManyField(related_name='team_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('OO', 'ONLINE'), ('AB', 'ABSTRACT BASED'), ('PB', 'PITCHING BASED'), ('HT', 'HACKATHON'), ('WS', 'WORKSHOP')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='payment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event/Certificate/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ManyToManyField(blank=True, to='events.CertImage'),
        ),
        migrations.DeleteModel(
            name='Workshop',
        ),
    ]
