# Generated by Django 3.1.7 on 2021-03-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210317_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='college',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='payment',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='selected',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
