# Generated by Django 3.1.7 on 2021-03-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('college', models.CharField(blank=True, max_length=150, null=True)),
                ('branch', models.CharField(blank=True, max_length=150, null=True)),
                ('semester', models.CharField(blank=True, max_length=20, null=True)),
                ('joined_team', models.BooleanField(default=False)),
                ('user_team_id', models.IntegerField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Robothon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('domain', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=10000)),
                ('requirements', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('selected', models.BooleanField(default=False)),
                ('abstract', models.FileField(null=True, upload_to='docs/robothon/abstracts')),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
