# Generated by Django 2.1.7 on 2020-02-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboPortal', '0003_auto_20200219_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_statement',
            name='requirements',
            field=models.TextField(max_length=2000),
        ),
    ]
