# Generated by Django 2.1.7 on 2020-02-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboPortal', '0005_auto_20200219_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abstract',
            field=models.FileField(default='', upload_to='docs/robothon/abstracts'),
        ),
    ]
