# Generated by Django 2.1.7 on 2020-02-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboPortal', '0006_team_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='abstract',
            field=models.FileField(null=True, upload_to='docs/robothon/abstracts'),
        ),
    ]
