# Generated by Django 2.2 on 2021-04-22 06:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url_key', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificate/')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('image_created', models.BooleanField(default=False, null=True)),
                ('email_sent', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
