# Generated by Django 3.2 on 2021-05-31 16:22

import certificate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_certificate_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=certificate.models.PathAndRename('certificate/')),
        ),
    ]
