# Generated by Django 2.2 on 2021-02-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
