# Generated by Django 2.2 on 2021-02-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0004_certificate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='email_send',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='image_created',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
