# Generated by Django 2.2 on 2021-02-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_auto_20210227_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='email_send',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='image_created',
        ),
    ]
