# Generated by Django 3.2 on 2021-05-05 13:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=1000)),
                ('candidate_mobile_number', models.CharField(max_length=10)),
                ('candidate_emailid', models.EmailField(max_length=254)),
                ('candidate_domain_choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=2)),
                ('question_all1', models.CharField(max_length=1000)),
                ('question_all2', models.CharField(max_length=1000)),
                ('question_all3', models.CharField(max_length=1000)),
                ('question_all4', models.CharField(max_length=1000)),
                ('question_all5', models.CharField(max_length=1000)),
                ('question_all6', models.CharField(max_length=1000)),
                ('question_web1', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_web2', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_web3', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_web4', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_web5', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_web6', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_core1', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_core2', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_core3', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_core4', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_core5', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_core6', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_design1', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_design2', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_design3', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_design4', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_design5', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_design6', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_docs1', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_docs2', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_docs3', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_docs4', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_docs5', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_docs6', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_pr1', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_pr2', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_pr3', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_pr4', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_pr5', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_pr6', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsForRecruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('question_type', models.CharField(choices=[('SingleChoice', 'SingleChoice'), ('MultipleChoice', 'MultipleChoice'), ('Answer', 'Answer')], max_length=1000)),
                ('question_for_domain', models.CharField(choices=[('Web', 'Web'), ('Core', 'Core'), ('Design', 'Design'), ('Docs', 'Docs'), ('PR', 'PR')], max_length=1000)),
                ('option1', models.CharField(blank=True, max_length=1000, null=True)),
                ('option2', models.CharField(blank=True, max_length=1000, null=True)),
                ('option3', models.CharField(blank=True, max_length=1000, null=True)),
                ('option4', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
