# Generated by Django 3.2.3 on 2021-06-07 15:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsForRecruitment',
            fields=[
                ('question', models.CharField(max_length=1000)),
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('SingleChoice', 'SingleChoice'), ('MultipleChoice', 'MultipleChoice'), ('Answer', 'Answer')], max_length=1000)),
                ('question_for_domain', models.CharField(choices=[('Web', 'Web'), ('Core', 'Core'), ('Design', 'Design'), ('Docs', 'Docs'), ('PR', 'PR')], max_length=1000)),
                ('option1', models.CharField(blank=True, max_length=1000)),
                ('option2', models.CharField(blank=True, max_length=1000)),
                ('option3', models.CharField(blank=True, max_length=1000)),
                ('option4', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedUser',
            fields=[
                ('candidate_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('candidate_name', models.CharField(max_length=1000)),
                ('candidate_mobile_number', models.CharField(max_length=10)),
                ('candidate_emailid', models.EmailField(max_length=254)),
                ('candidate_domain_choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=2)),
            ],
        ),
        migrations.CreateModel(
            name='FormResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_given', models.CharField(blank=True, max_length=20000)),
                ('options_answer_selected', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=4)),
                ('question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.questionsforrecruitment')),
                ('submitted_candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.submitteduser')),
            ],
        ),
    ]
