# Generated by Django 3.2.3 on 2021-06-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsforrecruitment',
            name='question_for_domain',
            field=models.CharField(choices=[('All', 'All'), ('Web', 'Web'), ('Core', 'Core'), ('Design', 'Design'), ('Docs', 'Docs'), ('PR', 'PR')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='questionsforrecruitment',
            name='question_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
