# Generated by Django 2.2 on 2021-04-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='img/team')),
                ('name', models.CharField(max_length=50, null=True)),
                ('branch', models.CharField(max_length=50, null=True)),
                ('domain_assign', models.CharField(choices=[('WA', 'WEB & APP'), ('PM', 'PR MARKETING'), ('DD', 'DOCUMENTATION'), ('SS', 'SPONSERSHIP'), ('DD', 'DESIGN'), ('TT', 'TECHNICAL')], max_length=2, null=True)),
                ('post_assign', models.CharField(choices=[('AA', 'Alumini'), ('CC', 'Convenor'), ('HC', 'HeadCoordinator'), ('MM', 'Manager'), ('CO', 'Coordinator')], max_length=2, null=True)),
                ('fb_id', models.URLField(null=True)),
                ('email_id', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('joining', models.DateField(null=True)),
            ],
        ),
    ]
