# Generated by Django 3.2 on 2021-05-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_achievements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='fb_id',
            new_name='fb_url',
        ),
        migrations.AddField(
            model_name='team',
            name='github_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='instagram_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(null=True, upload_to='about/team'),
        ),
    ]
