# Generated by Django 3.2 on 2021-05-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20210524_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='branch',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='domain_assign',
            field=models.CharField(choices=[('WA', 'WEB & APP'), ('PM', 'PR MARKETING'), ('DD', 'DOCUMENTATION'), ('SS', 'SPONSERSHIP'), ('DD', 'DESIGN'), ('TT', 'TECHNICAL')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='fb_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='post_assign',
            field=models.CharField(choices=[('AA', 'Alumini'), ('CC', 'Convenor'), ('HC', 'HeadCoordinator'), ('MM', 'Manager'), ('CO', 'Coordinator')], max_length=50, null=True),
        ),
    ]
