# Generated by Django 3.2 on 2021-05-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20210525_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='domain_assign',
            field=models.CharField(choices=[('WA', 'WEB & APP'), ('PM', 'PR MARKETING'), ('DO', 'DOCUMENTATION'), ('SS', 'SPONSERSHIP'), ('DV', 'DESIGN'), ('TT', 'TECHNICAL')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='post_assign',
            field=models.CharField(choices=[('AA', 'Alumini'), ('CC', 'Convenor'), ('HC', 'HeadCoordinator'), ('MM', 'Manager'), ('CO', 'Coordinator'), ('VO', 'Volunteer')], max_length=50, null=True),
        ),
    ]
