# Generated by Django 3.2 on 2021-05-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20210525_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='studying_year',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='post_assign',
            field=models.CharField(choices=[('AA', 'Alumini'), ('CC', 'Convenor'), ('HC', 'HeadCoordinator'), ('MM', 'Manager'), ('CO', 'Coordinator')], max_length=50, null=True),
        ),
    ]
