# Generated by Django 3.2 on 2021-05-31 16:22

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20210529_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(null=True, upload_to=about.models.PathAndRename('about/')),
        ),
    ]
