# Generated by Django 3.2.3 on 2021-06-07 15:18

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_team_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(null=True, upload_to=about.models.PathAndRename('about/team/')),
        ),
    ]
