# Generated by Django 3.2 on 2021-06-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_auto_20210607_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='post_assign',
            field=models.CharField(choices=[('AA', 'Alumini'), ('CC', 'Convenor'), ('MM', 'Manager'), ('CO', 'Coordinator')], max_length=50, null=True),
        ),
    ]
