# Generated by Django 2.1.7 on 2020-02-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(max_length=15)),
                ('college', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=50)),
                ('reason', models.TextField(default='', max_length=500)),
                ('rating', models.TextField(default='', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='recruitment',
        ),
    ]
