# Generated by Django 2.1.7 on 2020-03-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_auto_20200219_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=30)),
                ('semester', models.CharField(max_length=10)),
                ('domain', models.CharField(max_length=200)),
                ('intro', models.TextField(max_length=1000)),
                ('other_club_committee', models.TextField(max_length=1000)),
                ('strength_weakness', models.TextField(max_length=1000)),
                ('work', models.TextField(max_length=1000)),
                ('why_robotix', models.TextField(max_length=1000)),
                ('improvements_suggesions', models.TextField(max_length=1000)),
                ('residence', models.CharField(max_length=20)),
                ('priority', models.CharField(max_length=5)),
                ('priority_reason', models.CharField(max_length=25)),
                ('task_completion', models.CharField(max_length=5)),
                ('task_completion_reason', models.CharField(max_length=25)),
                ('intention', models.CharField(max_length=5)),
                ('intention_reason', models.CharField(max_length=25)),
            ],
        ),
    ]
