# Generated by Django 2.1.7 on 2020-03-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0006_auto_20200313_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='residence',
            field=models.CharField(max_length=100),
        ),
    ]
